package:
  name: smesh
  version: 6.7.2

source:
  path: ../..

build:

build:
  script_env:
    - CC
    - CXX

  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  binary_relocation: false [osx]
  features:
    - vc9               [win and py27]
    - vc10              [win and py34]
    - vc14              [win and py35]

requirements:
  build:
    - oce ==0.17.2
    - ninja
    - cmake
    - boost
    - netgen ==6.1
    - gcc-5 ==5.4.0     [linux or osx]
    - binutils ==2.26   [linux]
    - freetype ==2.5.5  [linux]

  run:
    - oce ==0.17.2
    - netgen ==6.1
    - libgcc-5 ==5.4.0    [linux or osx]

about:
  home: https://github.com/tpaviot/smesh
  license: LGPL
  summary: A complete MESH framework based on the OCE library.
