package:
  name: smesh
  version: 8.2.0

source:
  path: ../..

build:

build:
  script_env:
    - CC
    - CXX

  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  binary_relocation: false [osx]
  features:
    - vc9               [win and py27]
    - vc10              [win and py34]
    - vc14              [win and py35]

requirements:
  build:
    - oce ==0.18.1
    - ninja
    - vtk
    - cmake
    - boost ==1.64.0

  run:
    - oce ==0.18.1
    - vtk

about:
  home: https://github.com/tpaviot/smesh
  license: LGPL
  summary: A complete MESH framework based on the OCE library.
