language: cpp

cache:
 apt: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-4.0
    packages:
      - g++-5
      - g++-6
      - g++-7
      - clang-4.0
matrix:
  include:
  - os: linux
    compiler: gcc
    env: MATRIX_EVAL="CC=gcc && CXX=g++"
    dist: trusty
  - os: linux
    compiler: gcc
    env: MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    dist: trusty
  - os: linux
    compiler: gcc
    env: MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    dist: trusty
  - os: linux
    compiler: gcc
    env: MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    dist: trusty
  - os: linux
    compiler: clang
    env: MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"
    dist: trusty
  - env: ARCH="x86_64" MACOSX_DEPLOYMENT_TARGET="10.9"
    os: osx
    osx_image: xcode8.3

# Use miniconda to install binary versions of numpy etc. from continuum
# analytic's repository. Follows an approach described by Dan Blanchard:
# https://gist.github.com/dan-blanchard/7045057
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      eval "${MATRIX_EVAL}";
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh;
    fi
  - chmod +x miniconda.sh
  # When we are installing the 32 Bit conda on a 64 Bit system, the miniconda
  # installer will ask for a "yes" despite the -b flag, so we pipe in a yes
  - yes | ./miniconda.sh -b -p $HOME/miniconda
  #- bash miniconda.sh -b -p -f $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$HOME/miniconda/lib:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # install everything required to build the receipe
  - conda install conda-build anaconda-client
  # Useful for debugging any issues with conda
  - conda info -a
  # Add dlr-sc channel for third part libraries
  - conda config --add channels https://conda.anaconda.org/conda-forge
  - conda config --add channels https://conda.anaconda.org/dlr-sc
  - conda config --add channels https://conda.anaconda.org/oce
  
script:
  - conda build ci/conda  --dirty --no-remove-work-dir

after_success:
  - python ci/move-conda-package.py
  - anaconda -t $BINSTAR_TOKEN upload *.bz2 --force;

branches:
  only:
    - master
    - /^tp/
    - /^review/
