sudo: false

language: cpp

# the secure below is the binstar token
# to genrate this secure
# first create an anconda cloud token
# $ anaconda auth -n the_token_name -o oce -c --scopes api
# the token is return as something like "oc-6654-12334_111225"
# then encrypt the token
# You have to be in the directory where you installed the local copy of the repository
# $ cd [your_dev_dir]/oce-conda
# $ travis encrypt BINSTAR_TOKEN="oc-6654-12334_11122"
# !!be careful about the typo BINSTAR_TOKEN with the proper case. Otherwise
# !!the $BINSTAR_TOKEN env var value will be null and the line
# !!anaconda -t $BINSTAR_TOKEN upload *.bz2 will not be run properly
# after that, copy/paste the secure on the following line
env:
  global:
    - secure: "Q809gaR2XvFRsaZiuIm2VPB1lI6exjwlwcgvrg+oBRHdrcULKkE+cz1jN7aaC4owArzozE84+BPgRp0EbyL9JxibqXh+okBmz5dHtSscBZoE7X5V+vBVxfqcHQE7YADOqbUiSrbqlkFzXC7UedKGSmsdXSqipsWMyjblKKnyxd8="

matrix:
  include:
    - env: ARCH="x86_64"
      os: linux
      dist: trusty
    - env: ARCH="x86_64"
      os: osx
    - env: ARCH="x86_64"
      os: osx
      osx_image: xcode8.3

# Use miniconda to install binary versions of numpy etc. from continuum
# analytic's repository. Follows an approach described by Dan Blanchard:
# https://gist.github.com/dan-blanchard/7045057
before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh;
    fi;
  - chmod +x miniconda.sh
  # When we are installing the 32 Bit conda on a 64 Bit system, the miniconda
  # installer will ask for a "yes" despite the -b flag, so we pipe in a yes
  - yes | ./miniconda.sh -b -p $HOME/miniconda
  #- bash miniconda.sh -b -p -f $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$HOME/miniconda/lib:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # Add dlr-sc channel for third part libraries
  - conda config --add channels https://conda.anaconda.org/conda-forge
  - conda config --add channels https://conda.anaconda.org/dlr-sc
  - conda config --add channels https://conda.anaconda.org/oce
  # install everything required to build the receipe
  - conda install conda-build anaconda-client

script:
  - conda build ci/conda --no-remove-work-dir

after_success:
  - python ci/move-conda-package.py
  - anaconda -t $BINSTAR_TOKEN upload *.bz2 --force;

branches:
  only:
    - master
    - /^tp/
    - /^review/
